#pragma once


namespace —ñ‹“ {
	namespace ‰Æ•ó {
		public ref class ‰Æ•ó”Ô† {
		public:
			static const int Â¥”nå›ãJ = 0;
			static const int Â¥¼–{ = 1;
			static const int •Šy‘å• = 2;
			static const int ÔŠy‘‘D = 3;
			static const int ŠD”íìŒõ“V–Ú = 4;
			static const int ”’Šy•s“ñR = 5;
			static const int ÂˆäŒËÄ“c = 6;
			static const int —j•Ïˆî—t“V–Ú = 7;
			static const int ŠGu–ì‰K‰ÔšÔ = 8;
			static const int Ğ‰¨”’“V–Ú = 9;
			static const int ‘åˆäŒË‰Á‰ê = 10;
			static const int ÔŠyá•ô = 11;
			static const int “‚•¨O“úŒ = 12;
			static const int “‚•¨¼“‡ = 13;
			static const int l\Î = 14;
			static const int ¼‰Ô = 15;
			static const int ‹´—§ = 16;
			static const int ‹ã\‹ã”¯‰Öq = 17;
			static const int ìŒõ¬‰Öq = 18;
			static const int “‚•¨‰‰ÔŒ¨Õ = 19;
			static const int “‚•¨“èÄŒ¨Õ = 20;
			static const int “‚•¨V“cŒ¨Õ = 21;
			static const int “‚•¨¼‰®Œ¨Õ = 22;
			static const int “‚•¨•xm‰Öq = 23;
			static const int “‚•¨Ğ‰¨‰Öq = 24;
			static const int “‚•¨¨‚Œ¨Õ = 25;
			static const int “‚•¨’©‘q•¶—Ô = 26;
			static const int “‚•¨‰~ÀŒ¨Õ = 27;
			static const int “‚•¨‹Ê“°Œ¨Õ = 28;
			static const int “‚•¨ìŒõ•¶—Ô = 29;
			static const int ‘i‰Öq = 30;
			static const int ‘å—F•Z’\ = 31;
			static const int “‚•¨“à“Ü‘åŠC = 32;
			static const int —‚½‚è‰Öq = 33;
			static const int ²”ŒŒ¨Õ = 34;
			static const int ŒÃ“V–¾•½’wå = 35;
			static const int èÅ‰WŒûŠÛŠ˜ = 36;
			static const int Ä“›Š˜ = 37;
			static const int ˆ°‰®^Œ` = 38;
			static const int Â¥•“–³‚µ = 39;
			static const int ’|ˆêd‰~é› = 40;
			static const int Â¥‘å“à“› = 41;
			static const int ŒÃ“º’ßˆêº = 42;
			static const int ’|“ñd–é’· = 43;
			static const int ‰©£ŒË—·– = 44;
			static const int ‹SŠÛ = 45;
			static const int ‹gŒõœ‹ò = 46;
			static const int @O¶•¶š = 47;
			static const int ‘º³ = 48;
			static const int ŠÖ‚Ì‘·˜Z = 49;
			static const int ˜aòçŒ“’è = 50;
			static const int ˆ³Ø = 51;
			static const int ‰ZÀŒ• = 52;
			static const int ‰eG = 53;
			static const int ‰úñ“ = 54;
			static const int ¯Œ–é³@ = 55;
			static const int —‹Ø = 56;
			static const int “V‘ = 57;
			static const int ’|–“Œ“Œõ = 58;
			static const int ”õ‘O’·‘DŒ“Œõ = 59;
			static const int å‘åxØ = 60;
			static const int “ú–{† = 61;
			static const int •ĞŠ™‘„ = 62;
			static const int \•¶š‘„ = 63;
			static const int ‘òàb‘„ = 64;
			static const int •½“hŒÜ–‡“· = 65;
			static const int ‹à¬DFXˆĞ = 66;
			static const int ‹à‘É”ü‹ï‘« = 67;
			static const int ‰ÔF“ú‚ÌŠÛˆĞ = 68;
			static const int àçƒ‘fŒœˆĞ = 69;
			static const int ”’…‘fŒœˆĞ = 70;
			static const int g…ˆĞ¬• Šª = 71;
			static const int ã|…‰ºUgˆĞ = 72;
			static const int ¸’òq“ñ–‡“· = 73;
			static const int “ì”Ø“·‹ï‘« = 74;
			static const int ¼•— = 75;
			static const int ’éßŒI–Ñ = 76;
			static const int •ú¶Œ–Ñ = 77;
			static const int •‰_ = 78;
			static const int ¯è = 79;
			static const int …‹Êw”nD = 80;
			static const int ˆîÈŒ^ªŠGˆÆ = 81;
			static const int ‹àæEw”nD = 82;
			static const int ˆ°•äªŠGˆÆ = 83;
			static const int ˆáŠ™–äw”nD = 84;
			static const int Œ¹•¨Œê = 85;
			static const int ˆÉ¨•¨Œê = 86;
			static const int ŒÃ¡˜a‰ÌW = 87;
			static const int •½‰Æ•¨Œê = 88;
			static const int ‘¾•½‹L = 89;
			static const int ŒÃ–‹L = 90;
			static const int ‘·q = 91;
			static const int ˜Zèé = 92;
			static const int ‰©ÎŒöO—ª = 93;
			static const int Oš u‰‰‹` = 94;
			static const int j‹L = 95;
			static const int …Ÿõ“` = 96;
			static const int _‹È = 97;
			static const int “Œ•ûŒ©•·˜^ = 98;
			static const int ˆÉ‘\•Û•¨Œê = 99;
			static const int —–šø‘Ò = 100;
			static const int ’n‹…‹V = 101;
			static const int ’uŒv = 102;
			static const int ©–Âà = 103;
			static const int “”µ} = 104;
			static const int ànÃ–é‰J} = 105;
			static const int “´’ëHŒ} = 106;
			static const int ‰Œ›”Óà} = 107;
			static const int ‰“‰Y‹A”¿} = 108;
			static const int RsÂ—’} = 109;
			static const int ‹™‘º—[Æ} = 110;
			static const int •½¹—Šå} = 111;
			static const int ]“V•éá} = 112;
			static const int ƒJƒXƒeƒ‰ = 113;
			static const int ‹à•½“œ = 114;
			static const int ‰Ì—¯‘½ = 115;
			static const int ƒr[ƒhƒ”t = 116;
			static const int ‰“Šá‹¾ = 117;
			static const int ƒ‹ƒ\ƒ“šâ = 118;
			static const int “ú•’«‘ = 119;
		};
		public ref class í—Ş {
		public:
			static const int ’ƒ˜q = 0;
			static const int ’ƒšâ = 1;
			static const int ’ƒ“ü = 2;
			static const int ’ƒŠ˜ = 3;
			static const int ‰Ô“ü = 4;
			static const int “Œ• = 5;
			static const int ‘„ = 6;
			static const int ‹ï‘« = 7;
			static const int ”n = 8;
			static const int ˆÆ = 9;
			static const int w‰HD = 10;
			static const int Šªq–{ = 11;
			static const int –¾’©’Ô–{ = 12;
			static const int –Ø = 13;
			static const int ’n‹…‹V = 14;
			static const int “ì”ØŒv = 15;
			static const int …–n‰æ = 16;
			static const int ƒJƒXƒeƒ‰ = 17;
			static const int ‹à•½“œ = 18;
			static const int ‰Ì—¯‘½ = 19;
			static const int ƒr[ƒhƒ”t = 20;
			static const int ‰“Šá‹¾ = 21;
			static const int ƒ‹ƒ\ƒ“šâ = 22;
			static const int “ú•’«‘ = 23;
		};

		public ref class ‰æ‘œ {
		public:
			static const int ’ƒ˜q = 0;
			static const int ’ƒšâ = 1;
			static const int ’ƒ“ü = 2;
			static const int ’ƒŠ˜ = 3;
			static const int ‰Ô“ü = 4;
			static const int “Œ• = 5;
			static const int ‘„ = 6;
			static const int ‹ï‘« = 7;
			static const int ”n = 8;
			static const int ˆÆ = 9;
			static const int w‰HD = 10;
			static const int Šªq–{ = 11;
			static const int –¾’©’Ô–{ = 12;
			static const int …–n‰æ = 13;
			static const int “ì”ØŒv = 14;
			static const int ’n‹…‹V = 15;
			static const int “ú•’«‘ = 16;
			static const int ƒr[ƒhƒ”t = 17;
			static const int ƒJƒXƒeƒ‰ = 18;
			static const int ‰Ì—¯‘½ = 19;
			static const int ‰“Šá‹¾ = 20;
			static const int –Ø = 21;
		};
	}
}

